DROP TABLE IF EXISTS houses;

CREATE TABLE houses
(
    id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    name NVARCHAR(50) NOT NULL,
    image_name NVARCHAR(255) NOT NULL,
    description NVARCHAR(255) NOT NULL,
    price INT NOT NULL,
    capacity INT NOT NULL,
    postal_code NVARCHAR(50) NOT NULL,
    address NVARCHAR(255) NOT NULL,
    phone_number NVARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NOT NULL DEFAULT GETDATE()
);